#! /usr/bin/env perl

use strict;

use Getopt::Long qw(:config pass_through);

my $source;
my $dest;
my $help;

GetOptions("source=s" => \$source,
           "dest=s" => \$dest,
           "help|?" => \$help
    );

if($ARGV[0]) {
  print("ERROR: unknown option $ARGV[0]; aborting\n\n");
  printHelp();
  exit(1);
}

if($help) {
  printHelp();
  exit(0);
}

sub printHelp
{
  print "copyToRobot --source <file/directory to copy> \n\t--dest <";
  print "directory destination on robot> [--help]\n";
  print "\n\tNOTE: destination on robot is based on /home/lvuser\n";
  exit 1;
}

if(!$source || !$dest)
{
  print "ERROR: must provide source and dest\n";
  printHelp();
}

my $cmd = "scp -r $source lvuser\@10.49.5.2:/home/lvuser/$dest";
if(system($cmd))
{
  print "ERROR: $cmd failed.\n";
  exit 2;
}
print "SUCCESS\n";
exit 0;
