#! /usr/bin/env perl

use strict;

use Getopt::Long;

my $fileNumb;
my $help;
my $os = $^O;

GetOptions("fileNumb:i" => \$fileNumb,
           "help|?" => \$help,) or printHelp();

if($help) {
  printHelp();
}

sub printHelp
{
  print("\n$0 [--fileNumb <int>] [--help]\n");
  exit 1;
}

if(!$fileNumb) {
  $fileNumb = 0;
}
my $outputFile = "outputFile${fileNumb}.sed.sed.tr";
my $goldFile = "outputFile${fileNumb}.gold.sed.sed.tr";
my $backGround = "&";
if($os eq "linux") {
  $backGround = "";
}
my $cmd = "ediffBuffers $outputFile $goldFile $backGround";
print("\nCalling: \n\t$cmd\n\n");
system($cmd);
