#! /usr/bin/env perl

use strict;

use Getopt::Long;

my $fileNumb;
my $help;
my $os = $^O;

GetOptions("fileNumb:i" => \$fileNumb,
           "help|?" => \$help,) or printHelp();

if($help) {
  printHelp();
}

sub printHelp
{
  print("\n$0 [--fileNumb <int>] [--help]\n");
  exit 1;
}

if(!$fileNumb) {
  $fileNumb = 0;
}
my $filenameBase = "outputFile${fileNumb}";
my $sedStuff = "sed.sed.tr";
my $outputFile = "${filenameBase}.${sedStuff}";
my $goldFile = "${filenameBase}.gold.${sedStuff}";
if(-e "${filenameBase}.$sedStuff.sorted") {
  $outputFile = "${outputFile}.sorted";
  $goldFile = "${goldFile}.sorted";
}
my $backGround = "&";
if($os eq "linux") {
  $backGround = "";
}
my $cmd = "ediffBuffers $outputFile $goldFile $backGround";
print("\nCalling: \n\t$cmd\n\n");
system($cmd);
