#! /usr/bin/env perl

use strict;

my $scriptsPath = qx!cygpath -m "$ENV{'HOME'}/scripts"!;
chomp($scriptsPath);
my $cmd = "cmd /c \"${scriptsPath}/winHibernate.bat\"";
print("\nrunning cmd: $cmd\n");
system($cmd);
