#! /usr/bin/env bash

kill="no"
if [ $1 = "-k" ]; then
    kill="yes"
    shift
fi
regex=$1
if [ -z $regex ] ; then
    echo
    echo "ERROR: must provide process name regex"
    echo
    echo
    exit 1
fi

if [ $kill = "no" ]; then
    echo "Just listing processes; use -k to kill"
    echo
    tasklist.exe | egrep "$regex"
else
    echo "Killing processes"
    echo
    tasks=`tasklist.exe | egrep "$regex" | awk '{print $2}'`
    for task in $tasks; do
        taskkill /F /PID $task
    done
fi
exit 0
