#! /usr/bin/env bash

kill="no"
usage() {
    echo "Usage: $(basename "$0")  [-k] [-h] <process name>"
    exit
}

while getopts ":hk" arg; do
    case $arg in
        k)
            kill="yes"
            ;;
        h | *)
            usage
            exit 0
            ;;
    esac
done
# shift args to end to pick up positional arguments
shift $(($OPTIND - 1))

regex=$1
if [ -z $regex ] ; then
    echo
    echo "ERROR: must provide process name regex"
    echo
    echo
    exit 1
fi

if [ $kill = "no" ]; then
    echo "Just listing processes; use -k to kill"
    echo
    tasklist.exe | egrep "$regex"
else
    echo "Killing processes:"
    tasklist.exe | egrep "$regex"
    echo
    tasks=`tasklist.exe | egrep "$regex" | awk '{print $2}'`
    for task in $tasks; do
        cmd //c "taskkill /F /PID $task"
    done
fi
exit 0
