#! /usr/bin/env bash

usage() {
    echo "Usage: $(basename "$0")  [-h] target [link]"
    echo "if link not supplied, the basename of target will be used"
}

while getopts ":h" arg; do
    case $arg in
        h | *)
            usage
            exit 0
            ;;
    esac
done
# shift args to end to pick up positional arguments
shift $(($OPTIND - 1))
# first replace forward slashes with backslashes
if [ -z "$1" ]; then
    echo "ERROR: must provide target path"
    usage
    exit 1
fi
first=$1
# need to determine if this is an absolute path or a relative path, so check
# for leading /
if [[ "$first" = /* ]]; then
    echo "Source path is an absolute path: $first"
    # need to convert the drive letter to windows drive, so look for /<letter> and
    # convert to <letter>:
    driveLetter="${first:1:1}"
    # remove the leading /<letter> and replace with <letter>:
    first="${first:2}"
    first="${driveLetter}:${first}"
    echo "converted source path: $first"
fi
first=${first//\//\\}
second=$2
if [ -z "$2" ]; then
    # first remove a trailing / if it exists
    second="${1%/}"
    second="${second##*/}"
    echo "No link name supplied, using $second"
fi
second=${second//\//\\}
scriptsPath=`cygpath -m "$HOME/scripts"`
if [ -d "$1" ]; then
    myCmd="${scriptsPath}/symLinkDirectory.bat $first $second"
else
    myCmd="${scriptsPath}/symLinkFile.bat  $first $second"
fi
echo "Running $myCmd"
cmd //c "$myCmd"

