#!/usr/bin/env bash

function proml
{
	case $TERM in
		xterm*)
            hostname=`hostname`
            case $hostname in
                AAPi9UcoQ6nHHv2)
                    hostname="Laptop";;
                conw10tbdev01)
                    hostname="HugeServer";;
                cdcub22dtv01)
                    hostname="Ubuntu";;
                cdcry8tb01)
                    hostname="Rocky";;
                conw10regv01)
                    hostname="conbld1";;
                conw10regv02)
                    hostname="conbld2";;
                cdcw10simplore1)
                    hostname="canbld1";;
                cdcw10simplore2)
                    hostname="canbld2";;
            esac
			local TITLEBAR='\[\033]0;\u@$hostname:\w\007\]'
			;;
		*)
			local TITLEBAR=''
			;;
	esac
    export PS1="${TITLEBAR}\[$(tput bold)\]\[\033[38;5;39m\]\W\[$(tput sgr0)\]\[\033[38;5;93m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\[$(tput sgr0)\]: \[$(tput sgr0)\]"
}
