#!/usr/bin/env bash

function proml
{
	case $TERM in
		xterm*)
            hostname=`hostname`
            if [ "$hostname" == "AAPi9UcoQ6nHHv2" ]; then
                hostname="Laptop"
            fi
            if [ "$hostname" == "conw10tbdev01" ]; then
                hostname="HugeServer"
            fi
            if [ "$hostname" == "cdcub22dtv01" ]; then
                hostname="Ubuntu"
            fi
            if [ "$hostname" == "cdcry8tb01" ]; then
                hostname="Rocky"
            fi
			local TITLEBAR='\[\033]0;\u@$hostname:\w\007\]'
			;;
		*)
			local TITLEBAR=''
			;;
	esac
    export PS1="${TITLEBAR}\[$(tput bold)\]\[\033[38;5;39m\]\W\[$(tput sgr0)\]\[\033[38;5;93m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\[$(tput sgr0)\]: \[$(tput sgr0)\]"
}
