#!/usr/bin/env bash

function proml
{
	case $TERM in
		xterm*)
			local TITLEBAR='\[\033]0;\u@\h:\w\007\]'
			;;
		*)
			local TITLEBAR=''
			;;
	esac
#    export PS1="${TITLEBAR}\W: "
    export PS1="${TITLEBAR}\[\e[1m\]\W: \[\e[0m\]"
}


