#! /usr/bin/env perl

use strict;

use Getopt::Long;
use File::Basename;

my $deleteAll;
my $help;

my $scriptName = basename($0);

GetOptions("deleteAll" => \$deleteAll,
           "help|?" => \$help
    ) or printHelp();

printHelp() if($help);

sub printHelp
{
  print("\n$scriptName [--deleteAll] <junction>\n");
  print("\tdeleteAll : deletes all junctions in directory\n");
  exit
}

if($deleteAll)
{
  my $cmd = "find . -maxdepth 1 -type l -printf '\"%p\"\n'";
  my @output = qx/$cmd/;
  print("Junctions:\n @output");
  foreach my $junction(@output)
  {
    my $rmCmd = "rmJunction $junction";
    if(system($rmCmd))
    {
      print "ERROR: $rmCmd failed\n";
      exit 3;
    }
  }
  exit;
}

if(defined $ARGV[0] and length $ARGV[0])
{
  my $cmd = "/d/tools/WindowsSysInternals/junction64 -nobanner -d \"$ARGV[0]\"";
  if(system($cmd))
  {
    print("ERROR: $cmd failed\n");
    exit 1;
  }
}
else
{
  print "ERROR: must specify a junction to remove\n";
  exit 2;
}

