#! /usr/bin/env bash

export SIMPLORER_PERFORMANCE_METRIC_TOOL_ENV=1
/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Professional/Common7/IDE/devenv.exe ../DevTools/build/OfficialSln/SimplorerSolver.sln >/dev/null 2>&1 &
