#! /usr/bin/env bash

export MODELICA_TEST_HARNESS_MEMORY_LEAK_DETECTION_ENV=1
/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Professional/Common7/IDE/devenv.exe ../DevTools/build/OfficialSln/SimplorerSolver.sln &
